//
//  WKViewController.m
//  WKDocWriter
//
//  Created by Wyatt Kaufman on 2/1/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import "WKViewController.h"
#import <CoreText/CoreText.h>
#import "WKDocWriter.h"

@implementation WKViewController

- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
    // Release any cached data, images, etc that aren't in use.
}

#pragma mark - View lifecycle

- (void)viewDidLoad
{
}

-(IBAction)writeDemo:(id)sender
{
	NSMutableAttributedString *attrStr = [[NSMutableAttributedString alloc] initWithString:@"This is an attributed string."];
	CTFontRef boldFont = CTFontCreateWithName(CFSTR("Helvetica"), 17.0, NULL);
	[attrStr addAttribute:(id)kCTFontAttributeName value:(id)boldFont range:NSMakeRange(0, [attrStr length])];
	[attrStr addAttribute:(id)kCTForegroundColorAttributeName value:(id)[[UIColor redColor] CGColor] range:NSMakeRange(4, 4)];
	CTFontRef smallerfont = CTFontCreateWithName(CFSTR("Georgia-Italic"), 21.0, NULL);
	[attrStr addAttribute:(id)kCTFontAttributeName value:(id)smallerfont range:NSMakeRange(11, 17)];
	WKDocWriter *writer = [[WKDocWriter alloc] initWithAttributedString:attrStr];
	[writer write];
	[[writer docFormatData] writeToFile:[NSString stringWithFormat:@"/Users/%@/Desktop/test.doc", NSUserName()] atomically:NO];
	UIAlertView *alertView = [[UIAlertView alloc] initWithTitle:@"Document saved to desktop" message:@"Check your desktop for a sample document generated by WKDocWriter." delegate:nil cancelButtonTitle:@"OK" otherButtonTitles:nil, nil];
	[alertView show];
	[alertView release];
}


@end
